#include <stdio.h>
#include <stdlib.h>

/* 
 * Problem Description - 389 Find the Difference
 * 		Given two strings s and t which consist of only lowercase letters.
 * 		String t is generated by random shuffling string s and then add one more letter at a random position.
 *  	Find the letter that was added in t.
 *
 *
 * Notification for myself 
 * 	According it would be lowercase letters, 
 * 	only consider the 26 letters for computiing the ASCII code.
 */

char findTheDifference(char* s, char* t) 
{
	int i=0;
	int countS[26]={0}, countT[26]={0};

	while(s[0]!='\0')
	{
		char tmp=s[0];
		
		countS[tmp-97]++;
		s++;
	}

	while(t[0]!='\0')
	{
		char tmp=t[0];

		countT[tmp-97]++;
		t++;
	}

	for (i=0; i<26; i++)
	{
		if (countS[i]!=countT[i])
			return (i+97);
	}

	return 0;	
}

int main(void)
{
	char tmp;
	char str1[]="abcd";
	char str2[]="abcde";

	tmp = findTheDifference(str1, str2);

	printf("\nstr1:%s\nstr2:%s\n", str1, str2);
	printf("\nThe difference charactor is %c\n", tmp);
	return 0;
}
